### ISSUE TITLE
Hundreds of thousands of pings to "Mongo"

### ISSUE THREAD

**Issue by Fuad-R** [Daniel31x13/linkwarden#22]
All my DNS traffic goes through my PiHole, and after setting up linkwarden I noticed that it's making thousands of calls to "Mongo" about 2-3 per second. Do you know of any way to fix this?

![image](https://user-images.githubusercontent.com/90257746/211158313-bc1e3570-9dca-47a1-b91f-fd3a2d7107b5.png)

**Comment by Daniel31x13** [comment]
Hello @Fuad-R,
Sorry for the late response, there is a new version going to be released soon, I'm rebuilding everything from ground up and I hope you'll love it!

Being that said, this version is deprecated and sorry for the inconvenience...
